# Generated by Django 5.0.3 on 2024-03-22 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('discount', models.CharField(max_length=200, null=True)),
                ('unit_price', models.CharField(max_length=200, null=True)),
                ('prd_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oldd.category')),
            ],
        ),
    ]
