# Generated by Django 5.0.3 on 2024-03-22 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oldd', '0002_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_title',
        ),
    ]
